/*
Tenant mapper for HSP Logging 2.0

Service for managing tenants

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tenantmapper

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InputBillingEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputBillingEvent{}

// InputBillingEvent struct for InputBillingEvent
type InputBillingEvent struct {
	// Count
	Count int64 `json:"count"`
	// Organization, also known as tenant
	Organization string `json:"organization"`
	// Service
	Service string `json:"service"`
	// Source of the event
	Source *string `json:"source,omitempty"`
	// Timestamp
	Timestamp string `json:"timestamp"`
	// Unit of value (B, MB, GB). Default is `B`
	Unit *string `json:"unit,omitempty"`
	// Value
	Value int64 `json:"value"`
}

type _InputBillingEvent InputBillingEvent

// NewInputBillingEvent instantiates a new InputBillingEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputBillingEvent(count int64, organization string, service string, timestamp string, value int64) *InputBillingEvent {
	this := InputBillingEvent{}
	this.Count = count
	this.Organization = organization
	this.Service = service
	this.Timestamp = timestamp
	this.Value = value
	return &this
}

// NewInputBillingEventWithDefaults instantiates a new InputBillingEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputBillingEventWithDefaults() *InputBillingEvent {
	this := InputBillingEvent{}
	return &this
}

// GetCount returns the Count field value
func (o *InputBillingEvent) GetCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *InputBillingEvent) GetCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *InputBillingEvent) SetCount(v int64) {
	o.Count = v
}

// GetOrganization returns the Organization field value
func (o *InputBillingEvent) GetOrganization() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value
// and a boolean to check if the value has been set.
func (o *InputBillingEvent) GetOrganizationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Organization, true
}

// SetOrganization sets field value
func (o *InputBillingEvent) SetOrganization(v string) {
	o.Organization = v
}

// GetService returns the Service field value
func (o *InputBillingEvent) GetService() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Service
}

// GetServiceOk returns a tuple with the Service field value
// and a boolean to check if the value has been set.
func (o *InputBillingEvent) GetServiceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Service, true
}

// SetService sets field value
func (o *InputBillingEvent) SetService(v string) {
	o.Service = v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *InputBillingEvent) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputBillingEvent) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *InputBillingEvent) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *InputBillingEvent) SetSource(v string) {
	o.Source = &v
}

// GetTimestamp returns the Timestamp field value
func (o *InputBillingEvent) GetTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *InputBillingEvent) GetTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *InputBillingEvent) SetTimestamp(v string) {
	o.Timestamp = v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *InputBillingEvent) GetUnit() string {
	if o == nil || IsNil(o.Unit) {
		var ret string
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputBillingEvent) GetUnitOk() (*string, bool) {
	if o == nil || IsNil(o.Unit) {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *InputBillingEvent) HasUnit() bool {
	if o != nil && !IsNil(o.Unit) {
		return true
	}

	return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *InputBillingEvent) SetUnit(v string) {
	o.Unit = &v
}

// GetValue returns the Value field value
func (o *InputBillingEvent) GetValue() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *InputBillingEvent) GetValueOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *InputBillingEvent) SetValue(v int64) {
	o.Value = v
}

func (o InputBillingEvent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputBillingEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["organization"] = o.Organization
	toSerialize["service"] = o.Service
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	toSerialize["timestamp"] = o.Timestamp
	if !IsNil(o.Unit) {
		toSerialize["unit"] = o.Unit
	}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *InputBillingEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"organization",
		"service",
		"timestamp",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputBillingEvent := _InputBillingEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInputBillingEvent)

	if err != nil {
		return err
	}

	*o = InputBillingEvent(varInputBillingEvent)

	return err
}

type NullableInputBillingEvent struct {
	value *InputBillingEvent
	isSet bool
}

func (v NullableInputBillingEvent) Get() *InputBillingEvent {
	return v.value
}

func (v *NullableInputBillingEvent) Set(val *InputBillingEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableInputBillingEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableInputBillingEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputBillingEvent(val *InputBillingEvent) *NullableInputBillingEvent {
	return &NullableInputBillingEvent{value: val, isSet: true}
}

func (v NullableInputBillingEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputBillingEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
