/*
Tenant mapper for HSP Logging 2.0

Service for managing tenants

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tenantmapper

import (
	"encoding/json"
)

// checks if the TenantAPIKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantAPIKey{}

// TenantAPIKey struct for TenantAPIKey
type TenantAPIKey struct {
	// Who created this key
	Actor *string `json:"actor,omitempty"`
	// Description of the key
	Description *string `json:"description,omitempty"`
	// Unique key identifier
	Id *string `json:"id,omitempty"`
	// Last use of this key
	LastUsed *string `json:"last_used,omitempty"`
	// When this key was revoked
	RevokedAt *string `json:"revoked_at,omitempty"`
	// Scopes of the key
	Scopes *string `json:"scopes,omitempty"`
	// Signature of the key
	Signature *string `json:"signature,omitempty"`
	// Name of the tenant this key belongs to
	Tenant *string `json:"tenant,omitempty"`
}

// NewTenantAPIKey instantiates a new TenantAPIKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantAPIKey() *TenantAPIKey {
	this := TenantAPIKey{}
	return &this
}

// NewTenantAPIKeyWithDefaults instantiates a new TenantAPIKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantAPIKeyWithDefaults() *TenantAPIKey {
	this := TenantAPIKey{}
	return &this
}

// GetActor returns the Actor field value if set, zero value otherwise.
func (o *TenantAPIKey) GetActor() string {
	if o == nil || IsNil(o.Actor) {
		var ret string
		return ret
	}
	return *o.Actor
}

// GetActorOk returns a tuple with the Actor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAPIKey) GetActorOk() (*string, bool) {
	if o == nil || IsNil(o.Actor) {
		return nil, false
	}
	return o.Actor, true
}

// HasActor returns a boolean if a field has been set.
func (o *TenantAPIKey) HasActor() bool {
	if o != nil && !IsNil(o.Actor) {
		return true
	}

	return false
}

// SetActor gets a reference to the given string and assigns it to the Actor field.
func (o *TenantAPIKey) SetActor(v string) {
	o.Actor = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *TenantAPIKey) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAPIKey) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *TenantAPIKey) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *TenantAPIKey) SetDescription(v string) {
	o.Description = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TenantAPIKey) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAPIKey) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TenantAPIKey) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TenantAPIKey) SetId(v string) {
	o.Id = &v
}

// GetLastUsed returns the LastUsed field value if set, zero value otherwise.
func (o *TenantAPIKey) GetLastUsed() string {
	if o == nil || IsNil(o.LastUsed) {
		var ret string
		return ret
	}
	return *o.LastUsed
}

// GetLastUsedOk returns a tuple with the LastUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAPIKey) GetLastUsedOk() (*string, bool) {
	if o == nil || IsNil(o.LastUsed) {
		return nil, false
	}
	return o.LastUsed, true
}

// HasLastUsed returns a boolean if a field has been set.
func (o *TenantAPIKey) HasLastUsed() bool {
	if o != nil && !IsNil(o.LastUsed) {
		return true
	}

	return false
}

// SetLastUsed gets a reference to the given string and assigns it to the LastUsed field.
func (o *TenantAPIKey) SetLastUsed(v string) {
	o.LastUsed = &v
}

// GetRevokedAt returns the RevokedAt field value if set, zero value otherwise.
func (o *TenantAPIKey) GetRevokedAt() string {
	if o == nil || IsNil(o.RevokedAt) {
		var ret string
		return ret
	}
	return *o.RevokedAt
}

// GetRevokedAtOk returns a tuple with the RevokedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAPIKey) GetRevokedAtOk() (*string, bool) {
	if o == nil || IsNil(o.RevokedAt) {
		return nil, false
	}
	return o.RevokedAt, true
}

// HasRevokedAt returns a boolean if a field has been set.
func (o *TenantAPIKey) HasRevokedAt() bool {
	if o != nil && !IsNil(o.RevokedAt) {
		return true
	}

	return false
}

// SetRevokedAt gets a reference to the given string and assigns it to the RevokedAt field.
func (o *TenantAPIKey) SetRevokedAt(v string) {
	o.RevokedAt = &v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *TenantAPIKey) GetScopes() string {
	if o == nil || IsNil(o.Scopes) {
		var ret string
		return ret
	}
	return *o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAPIKey) GetScopesOk() (*string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *TenantAPIKey) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given string and assigns it to the Scopes field.
func (o *TenantAPIKey) SetScopes(v string) {
	o.Scopes = &v
}

// GetSignature returns the Signature field value if set, zero value otherwise.
func (o *TenantAPIKey) GetSignature() string {
	if o == nil || IsNil(o.Signature) {
		var ret string
		return ret
	}
	return *o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAPIKey) GetSignatureOk() (*string, bool) {
	if o == nil || IsNil(o.Signature) {
		return nil, false
	}
	return o.Signature, true
}

// HasSignature returns a boolean if a field has been set.
func (o *TenantAPIKey) HasSignature() bool {
	if o != nil && !IsNil(o.Signature) {
		return true
	}

	return false
}

// SetSignature gets a reference to the given string and assigns it to the Signature field.
func (o *TenantAPIKey) SetSignature(v string) {
	o.Signature = &v
}

// GetTenant returns the Tenant field value if set, zero value otherwise.
func (o *TenantAPIKey) GetTenant() string {
	if o == nil || IsNil(o.Tenant) {
		var ret string
		return ret
	}
	return *o.Tenant
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAPIKey) GetTenantOk() (*string, bool) {
	if o == nil || IsNil(o.Tenant) {
		return nil, false
	}
	return o.Tenant, true
}

// HasTenant returns a boolean if a field has been set.
func (o *TenantAPIKey) HasTenant() bool {
	if o != nil && !IsNil(o.Tenant) {
		return true
	}

	return false
}

// SetTenant gets a reference to the given string and assigns it to the Tenant field.
func (o *TenantAPIKey) SetTenant(v string) {
	o.Tenant = &v
}

func (o TenantAPIKey) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantAPIKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Actor) {
		toSerialize["actor"] = o.Actor
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LastUsed) {
		toSerialize["last_used"] = o.LastUsed
	}
	if !IsNil(o.RevokedAt) {
		toSerialize["revoked_at"] = o.RevokedAt
	}
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	if !IsNil(o.Signature) {
		toSerialize["signature"] = o.Signature
	}
	if !IsNil(o.Tenant) {
		toSerialize["tenant"] = o.Tenant
	}
	return toSerialize, nil
}

type NullableTenantAPIKey struct {
	value *TenantAPIKey
	isSet bool
}

func (v NullableTenantAPIKey) Get() *TenantAPIKey {
	return v.value
}

func (v *NullableTenantAPIKey) Set(val *TenantAPIKey) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantAPIKey) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantAPIKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantAPIKey(val *TenantAPIKey) *NullableTenantAPIKey {
	return &NullableTenantAPIKey{value: val, isSet: true}
}

func (v NullableTenantAPIKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantAPIKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
