/*
Tenant mapper for HSP Logging 2.0

Service for managing tenants

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tenantmapper

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RevokeKeyPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RevokeKeyPayload{}

// RevokeKeyPayload struct for RevokeKeyPayload
type RevokeKeyPayload struct {
	// The key to revoke
	Key string `json:"key"`
}

type _RevokeKeyPayload RevokeKeyPayload

// NewRevokeKeyPayload instantiates a new RevokeKeyPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRevokeKeyPayload(key string) *RevokeKeyPayload {
	this := RevokeKeyPayload{}
	this.Key = key
	return &this
}

// NewRevokeKeyPayloadWithDefaults instantiates a new RevokeKeyPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRevokeKeyPayloadWithDefaults() *RevokeKeyPayload {
	this := RevokeKeyPayload{}
	return &this
}

// GetKey returns the Key field value
func (o *RevokeKeyPayload) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *RevokeKeyPayload) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *RevokeKeyPayload) SetKey(v string) {
	o.Key = v
}

func (o RevokeKeyPayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RevokeKeyPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	return toSerialize, nil
}

func (o *RevokeKeyPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRevokeKeyPayload := _RevokeKeyPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRevokeKeyPayload)

	if err != nil {
		return err
	}

	*o = RevokeKeyPayload(varRevokeKeyPayload)

	return err
}

type NullableRevokeKeyPayload struct {
	value *RevokeKeyPayload
	isSet bool
}

func (v NullableRevokeKeyPayload) Get() *RevokeKeyPayload {
	return v.value
}

func (v *NullableRevokeKeyPayload) Set(val *RevokeKeyPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableRevokeKeyPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableRevokeKeyPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRevokeKeyPayload(val *RevokeKeyPayload) *NullableRevokeKeyPayload {
	return &NullableRevokeKeyPayload{value: val, isSet: true}
}

func (v NullableRevokeKeyPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRevokeKeyPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
