/*
Tenant mapper for HSP Logging 2.0

Service for managing tenants

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tenantmapper

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateKeyPayload2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateKeyPayload2{}

// CreateKeyPayload2 struct for CreateKeyPayload2
type CreateKeyPayload2 struct {
	// The admin user
	Admin string `json:"admin"`
	// Expiry time time.Duration format. A value of 0s means no expiry
	Expiry string `json:"expiry"`
	// The format of the key
	Format string `json:"format"`
}

type _CreateKeyPayload2 CreateKeyPayload2

// NewCreateKeyPayload2 instantiates a new CreateKeyPayload2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateKeyPayload2(admin string, expiry string, format string) *CreateKeyPayload2 {
	this := CreateKeyPayload2{}
	this.Admin = admin
	this.Expiry = expiry
	this.Format = format
	return &this
}

// NewCreateKeyPayload2WithDefaults instantiates a new CreateKeyPayload2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateKeyPayload2WithDefaults() *CreateKeyPayload2 {
	this := CreateKeyPayload2{}
	return &this
}

// GetAdmin returns the Admin field value
func (o *CreateKeyPayload2) GetAdmin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Admin
}

// GetAdminOk returns a tuple with the Admin field value
// and a boolean to check if the value has been set.
func (o *CreateKeyPayload2) GetAdminOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Admin, true
}

// SetAdmin sets field value
func (o *CreateKeyPayload2) SetAdmin(v string) {
	o.Admin = v
}

// GetExpiry returns the Expiry field value
func (o *CreateKeyPayload2) GetExpiry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Expiry
}

// GetExpiryOk returns a tuple with the Expiry field value
// and a boolean to check if the value has been set.
func (o *CreateKeyPayload2) GetExpiryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expiry, true
}

// SetExpiry sets field value
func (o *CreateKeyPayload2) SetExpiry(v string) {
	o.Expiry = v
}

// GetFormat returns the Format field value
func (o *CreateKeyPayload2) GetFormat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Format
}

// GetFormatOk returns a tuple with the Format field value
// and a boolean to check if the value has been set.
func (o *CreateKeyPayload2) GetFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Format, true
}

// SetFormat sets field value
func (o *CreateKeyPayload2) SetFormat(v string) {
	o.Format = v
}

func (o CreateKeyPayload2) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateKeyPayload2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["admin"] = o.Admin
	toSerialize["expiry"] = o.Expiry
	toSerialize["format"] = o.Format
	return toSerialize, nil
}

func (o *CreateKeyPayload2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"admin",
		"expiry",
		"format",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateKeyPayload2 := _CreateKeyPayload2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateKeyPayload2)

	if err != nil {
		return err
	}

	*o = CreateKeyPayload2(varCreateKeyPayload2)

	return err
}

type NullableCreateKeyPayload2 struct {
	value *CreateKeyPayload2
	isSet bool
}

func (v NullableCreateKeyPayload2) Get() *CreateKeyPayload2 {
	return v.value
}

func (v *NullableCreateKeyPayload2) Set(val *CreateKeyPayload2) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateKeyPayload2) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateKeyPayload2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateKeyPayload2(val *CreateKeyPayload2) *NullableCreateKeyPayload2 {
	return &NullableCreateKeyPayload2{value: val, isSet: true}
}

func (v NullableCreateKeyPayload2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateKeyPayload2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
