/*
Tenant mapper for HSP Logging 2.0

Service for managing tenants

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tenantmapper

import (
	"encoding/json"
)

// checks if the Tenant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Tenant{}

// Tenant struct for Tenant
type Tenant struct {
	// The admin claim of the tenant
	AdminClaim *string `json:"admin_claim,omitempty"`
	// Comma separated list of admins
	Admins *string `json:"admins,omitempty"`
	// The editor claim of the tenant
	EditorClaim *string `json:"editor_claim,omitempty"`
	// The GUID of the IDP
	Guid *string `json:"guid,omitempty"`
	// Unique account identifier
	Id *string `json:"id,omitempty"`
	// The log retention period of the tenant, format is Go's time.Duration
	LogRetentionPeriod *string `json:"log_retention_period,omitempty"`
	// Logging enabled
	Logging *bool `json:"logging,omitempty"`
	// Metrics enabled
	Metrics *bool `json:"metrics,omitempty"`
	// The metrics retention period of the tenant, format is Go's time.Duration
	MetricsRetentionPeriod *string `json:"metrics_retention_period,omitempty"`
	// Name of the tenant
	Name *string `json:"name,omitempty"`
	// The Org ID of the application
	OrgId *int64 `json:"org_id,omitempty"`
	// Profiles enabled
	Profiles *bool `json:"profiles,omitempty"`
	// The trace retention period of the tenant, format is Go's time.Duration
	TraceRetentionPeriod *string `json:"trace_retention_period,omitempty"`
	// Tracing enabled
	Tracing *bool `json:"tracing,omitempty"`
	// The viewer claim of the tenant
	ViewerClaim *string `json:"viewer_claim,omitempty"`
}

// NewTenant instantiates a new Tenant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenant() *Tenant {
	this := Tenant{}
	return &this
}

// NewTenantWithDefaults instantiates a new Tenant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantWithDefaults() *Tenant {
	this := Tenant{}
	return &this
}

// GetAdminClaim returns the AdminClaim field value if set, zero value otherwise.
func (o *Tenant) GetAdminClaim() string {
	if o == nil || IsNil(o.AdminClaim) {
		var ret string
		return ret
	}
	return *o.AdminClaim
}

// GetAdminClaimOk returns a tuple with the AdminClaim field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tenant) GetAdminClaimOk() (*string, bool) {
	if o == nil || IsNil(o.AdminClaim) {
		return nil, false
	}
	return o.AdminClaim, true
}

// HasAdminClaim returns a boolean if a field has been set.
func (o *Tenant) HasAdminClaim() bool {
	if o != nil && !IsNil(o.AdminClaim) {
		return true
	}

	return false
}

// SetAdminClaim gets a reference to the given string and assigns it to the AdminClaim field.
func (o *Tenant) SetAdminClaim(v string) {
	o.AdminClaim = &v
}

// GetAdmins returns the Admins field value if set, zero value otherwise.
func (o *Tenant) GetAdmins() string {
	if o == nil || IsNil(o.Admins) {
		var ret string
		return ret
	}
	return *o.Admins
}

// GetAdminsOk returns a tuple with the Admins field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tenant) GetAdminsOk() (*string, bool) {
	if o == nil || IsNil(o.Admins) {
		return nil, false
	}
	return o.Admins, true
}

// HasAdmins returns a boolean if a field has been set.
func (o *Tenant) HasAdmins() bool {
	if o != nil && !IsNil(o.Admins) {
		return true
	}

	return false
}

// SetAdmins gets a reference to the given string and assigns it to the Admins field.
func (o *Tenant) SetAdmins(v string) {
	o.Admins = &v
}

// GetEditorClaim returns the EditorClaim field value if set, zero value otherwise.
func (o *Tenant) GetEditorClaim() string {
	if o == nil || IsNil(o.EditorClaim) {
		var ret string
		return ret
	}
	return *o.EditorClaim
}

// GetEditorClaimOk returns a tuple with the EditorClaim field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tenant) GetEditorClaimOk() (*string, bool) {
	if o == nil || IsNil(o.EditorClaim) {
		return nil, false
	}
	return o.EditorClaim, true
}

// HasEditorClaim returns a boolean if a field has been set.
func (o *Tenant) HasEditorClaim() bool {
	if o != nil && !IsNil(o.EditorClaim) {
		return true
	}

	return false
}

// SetEditorClaim gets a reference to the given string and assigns it to the EditorClaim field.
func (o *Tenant) SetEditorClaim(v string) {
	o.EditorClaim = &v
}

// GetGuid returns the Guid field value if set, zero value otherwise.
func (o *Tenant) GetGuid() string {
	if o == nil || IsNil(o.Guid) {
		var ret string
		return ret
	}
	return *o.Guid
}

// GetGuidOk returns a tuple with the Guid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tenant) GetGuidOk() (*string, bool) {
	if o == nil || IsNil(o.Guid) {
		return nil, false
	}
	return o.Guid, true
}

// HasGuid returns a boolean if a field has been set.
func (o *Tenant) HasGuid() bool {
	if o != nil && !IsNil(o.Guid) {
		return true
	}

	return false
}

// SetGuid gets a reference to the given string and assigns it to the Guid field.
func (o *Tenant) SetGuid(v string) {
	o.Guid = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Tenant) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tenant) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Tenant) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Tenant) SetId(v string) {
	o.Id = &v
}

// GetLogRetentionPeriod returns the LogRetentionPeriod field value if set, zero value otherwise.
func (o *Tenant) GetLogRetentionPeriod() string {
	if o == nil || IsNil(o.LogRetentionPeriod) {
		var ret string
		return ret
	}
	return *o.LogRetentionPeriod
}

// GetLogRetentionPeriodOk returns a tuple with the LogRetentionPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tenant) GetLogRetentionPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.LogRetentionPeriod) {
		return nil, false
	}
	return o.LogRetentionPeriod, true
}

// HasLogRetentionPeriod returns a boolean if a field has been set.
func (o *Tenant) HasLogRetentionPeriod() bool {
	if o != nil && !IsNil(o.LogRetentionPeriod) {
		return true
	}

	return false
}

// SetLogRetentionPeriod gets a reference to the given string and assigns it to the LogRetentionPeriod field.
func (o *Tenant) SetLogRetentionPeriod(v string) {
	o.LogRetentionPeriod = &v
}

// GetLogging returns the Logging field value if set, zero value otherwise.
func (o *Tenant) GetLogging() bool {
	if o == nil || IsNil(o.Logging) {
		var ret bool
		return ret
	}
	return *o.Logging
}

// GetLoggingOk returns a tuple with the Logging field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tenant) GetLoggingOk() (*bool, bool) {
	if o == nil || IsNil(o.Logging) {
		return nil, false
	}
	return o.Logging, true
}

// HasLogging returns a boolean if a field has been set.
func (o *Tenant) HasLogging() bool {
	if o != nil && !IsNil(o.Logging) {
		return true
	}

	return false
}

// SetLogging gets a reference to the given bool and assigns it to the Logging field.
func (o *Tenant) SetLogging(v bool) {
	o.Logging = &v
}

// GetMetrics returns the Metrics field value if set, zero value otherwise.
func (o *Tenant) GetMetrics() bool {
	if o == nil || IsNil(o.Metrics) {
		var ret bool
		return ret
	}
	return *o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tenant) GetMetricsOk() (*bool, bool) {
	if o == nil || IsNil(o.Metrics) {
		return nil, false
	}
	return o.Metrics, true
}

// HasMetrics returns a boolean if a field has been set.
func (o *Tenant) HasMetrics() bool {
	if o != nil && !IsNil(o.Metrics) {
		return true
	}

	return false
}

// SetMetrics gets a reference to the given bool and assigns it to the Metrics field.
func (o *Tenant) SetMetrics(v bool) {
	o.Metrics = &v
}

// GetMetricsRetentionPeriod returns the MetricsRetentionPeriod field value if set, zero value otherwise.
func (o *Tenant) GetMetricsRetentionPeriod() string {
	if o == nil || IsNil(o.MetricsRetentionPeriod) {
		var ret string
		return ret
	}
	return *o.MetricsRetentionPeriod
}

// GetMetricsRetentionPeriodOk returns a tuple with the MetricsRetentionPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tenant) GetMetricsRetentionPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.MetricsRetentionPeriod) {
		return nil, false
	}
	return o.MetricsRetentionPeriod, true
}

// HasMetricsRetentionPeriod returns a boolean if a field has been set.
func (o *Tenant) HasMetricsRetentionPeriod() bool {
	if o != nil && !IsNil(o.MetricsRetentionPeriod) {
		return true
	}

	return false
}

// SetMetricsRetentionPeriod gets a reference to the given string and assigns it to the MetricsRetentionPeriod field.
func (o *Tenant) SetMetricsRetentionPeriod(v string) {
	o.MetricsRetentionPeriod = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Tenant) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tenant) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Tenant) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Tenant) SetName(v string) {
	o.Name = &v
}

// GetOrgId returns the OrgId field value if set, zero value otherwise.
func (o *Tenant) GetOrgId() int64 {
	if o == nil || IsNil(o.OrgId) {
		var ret int64
		return ret
	}
	return *o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tenant) GetOrgIdOk() (*int64, bool) {
	if o == nil || IsNil(o.OrgId) {
		return nil, false
	}
	return o.OrgId, true
}

// HasOrgId returns a boolean if a field has been set.
func (o *Tenant) HasOrgId() bool {
	if o != nil && !IsNil(o.OrgId) {
		return true
	}

	return false
}

// SetOrgId gets a reference to the given int64 and assigns it to the OrgId field.
func (o *Tenant) SetOrgId(v int64) {
	o.OrgId = &v
}

// GetProfiles returns the Profiles field value if set, zero value otherwise.
func (o *Tenant) GetProfiles() bool {
	if o == nil || IsNil(o.Profiles) {
		var ret bool
		return ret
	}
	return *o.Profiles
}

// GetProfilesOk returns a tuple with the Profiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tenant) GetProfilesOk() (*bool, bool) {
	if o == nil || IsNil(o.Profiles) {
		return nil, false
	}
	return o.Profiles, true
}

// HasProfiles returns a boolean if a field has been set.
func (o *Tenant) HasProfiles() bool {
	if o != nil && !IsNil(o.Profiles) {
		return true
	}

	return false
}

// SetProfiles gets a reference to the given bool and assigns it to the Profiles field.
func (o *Tenant) SetProfiles(v bool) {
	o.Profiles = &v
}

// GetTraceRetentionPeriod returns the TraceRetentionPeriod field value if set, zero value otherwise.
func (o *Tenant) GetTraceRetentionPeriod() string {
	if o == nil || IsNil(o.TraceRetentionPeriod) {
		var ret string
		return ret
	}
	return *o.TraceRetentionPeriod
}

// GetTraceRetentionPeriodOk returns a tuple with the TraceRetentionPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tenant) GetTraceRetentionPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.TraceRetentionPeriod) {
		return nil, false
	}
	return o.TraceRetentionPeriod, true
}

// HasTraceRetentionPeriod returns a boolean if a field has been set.
func (o *Tenant) HasTraceRetentionPeriod() bool {
	if o != nil && !IsNil(o.TraceRetentionPeriod) {
		return true
	}

	return false
}

// SetTraceRetentionPeriod gets a reference to the given string and assigns it to the TraceRetentionPeriod field.
func (o *Tenant) SetTraceRetentionPeriod(v string) {
	o.TraceRetentionPeriod = &v
}

// GetTracing returns the Tracing field value if set, zero value otherwise.
func (o *Tenant) GetTracing() bool {
	if o == nil || IsNil(o.Tracing) {
		var ret bool
		return ret
	}
	return *o.Tracing
}

// GetTracingOk returns a tuple with the Tracing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tenant) GetTracingOk() (*bool, bool) {
	if o == nil || IsNil(o.Tracing) {
		return nil, false
	}
	return o.Tracing, true
}

// HasTracing returns a boolean if a field has been set.
func (o *Tenant) HasTracing() bool {
	if o != nil && !IsNil(o.Tracing) {
		return true
	}

	return false
}

// SetTracing gets a reference to the given bool and assigns it to the Tracing field.
func (o *Tenant) SetTracing(v bool) {
	o.Tracing = &v
}

// GetViewerClaim returns the ViewerClaim field value if set, zero value otherwise.
func (o *Tenant) GetViewerClaim() string {
	if o == nil || IsNil(o.ViewerClaim) {
		var ret string
		return ret
	}
	return *o.ViewerClaim
}

// GetViewerClaimOk returns a tuple with the ViewerClaim field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tenant) GetViewerClaimOk() (*string, bool) {
	if o == nil || IsNil(o.ViewerClaim) {
		return nil, false
	}
	return o.ViewerClaim, true
}

// HasViewerClaim returns a boolean if a field has been set.
func (o *Tenant) HasViewerClaim() bool {
	if o != nil && !IsNil(o.ViewerClaim) {
		return true
	}

	return false
}

// SetViewerClaim gets a reference to the given string and assigns it to the ViewerClaim field.
func (o *Tenant) SetViewerClaim(v string) {
	o.ViewerClaim = &v
}

func (o Tenant) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Tenant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AdminClaim) {
		toSerialize["admin_claim"] = o.AdminClaim
	}
	if !IsNil(o.Admins) {
		toSerialize["admins"] = o.Admins
	}
	if !IsNil(o.EditorClaim) {
		toSerialize["editor_claim"] = o.EditorClaim
	}
	if !IsNil(o.Guid) {
		toSerialize["guid"] = o.Guid
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LogRetentionPeriod) {
		toSerialize["log_retention_period"] = o.LogRetentionPeriod
	}
	if !IsNil(o.Logging) {
		toSerialize["logging"] = o.Logging
	}
	if !IsNil(o.Metrics) {
		toSerialize["metrics"] = o.Metrics
	}
	if !IsNil(o.MetricsRetentionPeriod) {
		toSerialize["metrics_retention_period"] = o.MetricsRetentionPeriod
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.OrgId) {
		toSerialize["org_id"] = o.OrgId
	}
	if !IsNil(o.Profiles) {
		toSerialize["profiles"] = o.Profiles
	}
	if !IsNil(o.TraceRetentionPeriod) {
		toSerialize["trace_retention_period"] = o.TraceRetentionPeriod
	}
	if !IsNil(o.Tracing) {
		toSerialize["tracing"] = o.Tracing
	}
	if !IsNil(o.ViewerClaim) {
		toSerialize["viewer_claim"] = o.ViewerClaim
	}
	return toSerialize, nil
}

type NullableTenant struct {
	value *Tenant
	isSet bool
}

func (v NullableTenant) Get() *Tenant {
	return v.value
}

func (v *NullableTenant) Set(val *Tenant) {
	v.value = val
	v.isSet = true
}

func (v NullableTenant) IsSet() bool {
	return v.isSet
}

func (v *NullableTenant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenant(val *Tenant) *NullableTenant {
	return &NullableTenant{value: val, isSet: true}
}

func (v NullableTenant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
