/*
Tenant mapper for HSP Logging 2.0

Service for managing tenants

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tenantmapper

import (
	"encoding/json"
)

// checks if the GeneratedKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeneratedKey{}

// GeneratedKey struct for GeneratedKey
type GeneratedKey struct {
	// The format of the key
	Format *string `json:"format,omitempty"`
	// The generated key
	Key *string `json:"key,omitempty"`
	// The signature of the key
	Signature *string `json:"signature,omitempty"`
	// The version of the key
	Version *string `json:"version,omitempty"`
}

// NewGeneratedKey instantiates a new GeneratedKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeneratedKey() *GeneratedKey {
	this := GeneratedKey{}
	return &this
}

// NewGeneratedKeyWithDefaults instantiates a new GeneratedKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeneratedKeyWithDefaults() *GeneratedKey {
	this := GeneratedKey{}
	return &this
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *GeneratedKey) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneratedKey) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *GeneratedKey) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *GeneratedKey) SetFormat(v string) {
	o.Format = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *GeneratedKey) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneratedKey) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *GeneratedKey) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *GeneratedKey) SetKey(v string) {
	o.Key = &v
}

// GetSignature returns the Signature field value if set, zero value otherwise.
func (o *GeneratedKey) GetSignature() string {
	if o == nil || IsNil(o.Signature) {
		var ret string
		return ret
	}
	return *o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneratedKey) GetSignatureOk() (*string, bool) {
	if o == nil || IsNil(o.Signature) {
		return nil, false
	}
	return o.Signature, true
}

// HasSignature returns a boolean if a field has been set.
func (o *GeneratedKey) HasSignature() bool {
	if o != nil && !IsNil(o.Signature) {
		return true
	}

	return false
}

// SetSignature gets a reference to the given string and assigns it to the Signature field.
func (o *GeneratedKey) SetSignature(v string) {
	o.Signature = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *GeneratedKey) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneratedKey) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *GeneratedKey) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *GeneratedKey) SetVersion(v string) {
	o.Version = &v
}

func (o GeneratedKey) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeneratedKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Signature) {
		toSerialize["signature"] = o.Signature
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableGeneratedKey struct {
	value *GeneratedKey
	isSet bool
}

func (v NullableGeneratedKey) Get() *GeneratedKey {
	return v.value
}

func (v *NullableGeneratedKey) Set(val *GeneratedKey) {
	v.value = val
	v.isSet = true
}

func (v NullableGeneratedKey) IsSet() bool {
	return v.isSet
}

func (v *NullableGeneratedKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeneratedKey(val *GeneratedKey) *NullableGeneratedKey {
	return &NullableGeneratedKey{value: val, isSet: true}
}

func (v NullableGeneratedKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeneratedKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
