/*
Tenant mapper for HSP Logging 2.0

Service for managing tenants

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tenantmapper

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InputKeyPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputKeyPayload{}

// InputKeyPayload struct for InputKeyPayload
type InputKeyPayload struct {
	// The key to verify
	Key string `json:"key"`
}

type _InputKeyPayload InputKeyPayload

// NewInputKeyPayload instantiates a new InputKeyPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputKeyPayload(key string) *InputKeyPayload {
	this := InputKeyPayload{}
	this.Key = key
	return &this
}

// NewInputKeyPayloadWithDefaults instantiates a new InputKeyPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputKeyPayloadWithDefaults() *InputKeyPayload {
	this := InputKeyPayload{}
	return &this
}

// GetKey returns the Key field value
func (o *InputKeyPayload) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *InputKeyPayload) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *InputKeyPayload) SetKey(v string) {
	o.Key = v
}

func (o InputKeyPayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputKeyPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	return toSerialize, nil
}

func (o *InputKeyPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputKeyPayload := _InputKeyPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInputKeyPayload)

	if err != nil {
		return err
	}

	*o = InputKeyPayload(varInputKeyPayload)

	return err
}

type NullableInputKeyPayload struct {
	value *InputKeyPayload
	isSet bool
}

func (v NullableInputKeyPayload) Get() *InputKeyPayload {
	return v.value
}

func (v *NullableInputKeyPayload) Set(val *InputKeyPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableInputKeyPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableInputKeyPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputKeyPayload(val *InputKeyPayload) *NullableInputKeyPayload {
	return &NullableInputKeyPayload{value: val, isSet: true}
}

func (v NullableInputKeyPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputKeyPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
