/*
Tenant mapper for HSP Logging 2.0

Service for managing tenants

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tenantmapper

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OnboardTenantPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OnboardTenantPayload{}

// OnboardTenantPayload struct for OnboardTenantPayload
type OnboardTenantPayload struct {
	// Comma separated list of authorized admins
	Admins *string `json:"admins,omitempty"`
	// The AWS region to onboard onto
	AwsRegion string `json:"aws_region"`
	// The GitHub editor team
	GhEditorTeam *string `json:"gh_editor_team,omitempty"`
	// The GitHub viewer team
	GhViewerTeam *string `json:"gh_viewer_team,omitempty"`
	// The IAM Org ID
	IamOrgId *string `json:"iam_org_id,omitempty"`
	// ID token
	IdToken string `json:"id_token"`
	// The log retention period of the tenant
	LogRetention *string `json:"log_retention,omitempty"`
	// The metrics retention period of the tenant
	MetricsRetention *string `json:"metrics_retention,omitempty"`
	// Tenant name
	Name string `json:"name"`
	// The tracing retention period of the tenant
	TraceRetention *string `json:"trace_retention,omitempty"`
}

type _OnboardTenantPayload OnboardTenantPayload

// NewOnboardTenantPayload instantiates a new OnboardTenantPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOnboardTenantPayload(awsRegion string, idToken string, name string) *OnboardTenantPayload {
	this := OnboardTenantPayload{}
	this.AwsRegion = awsRegion
	this.IdToken = idToken
	this.Name = name
	return &this
}

// NewOnboardTenantPayloadWithDefaults instantiates a new OnboardTenantPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOnboardTenantPayloadWithDefaults() *OnboardTenantPayload {
	this := OnboardTenantPayload{}
	return &this
}

// GetAdmins returns the Admins field value if set, zero value otherwise.
func (o *OnboardTenantPayload) GetAdmins() string {
	if o == nil || IsNil(o.Admins) {
		var ret string
		return ret
	}
	return *o.Admins
}

// GetAdminsOk returns a tuple with the Admins field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OnboardTenantPayload) GetAdminsOk() (*string, bool) {
	if o == nil || IsNil(o.Admins) {
		return nil, false
	}
	return o.Admins, true
}

// HasAdmins returns a boolean if a field has been set.
func (o *OnboardTenantPayload) HasAdmins() bool {
	if o != nil && !IsNil(o.Admins) {
		return true
	}

	return false
}

// SetAdmins gets a reference to the given string and assigns it to the Admins field.
func (o *OnboardTenantPayload) SetAdmins(v string) {
	o.Admins = &v
}

// GetAwsRegion returns the AwsRegion field value
func (o *OnboardTenantPayload) GetAwsRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AwsRegion
}

// GetAwsRegionOk returns a tuple with the AwsRegion field value
// and a boolean to check if the value has been set.
func (o *OnboardTenantPayload) GetAwsRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AwsRegion, true
}

// SetAwsRegion sets field value
func (o *OnboardTenantPayload) SetAwsRegion(v string) {
	o.AwsRegion = v
}

// GetGhEditorTeam returns the GhEditorTeam field value if set, zero value otherwise.
func (o *OnboardTenantPayload) GetGhEditorTeam() string {
	if o == nil || IsNil(o.GhEditorTeam) {
		var ret string
		return ret
	}
	return *o.GhEditorTeam
}

// GetGhEditorTeamOk returns a tuple with the GhEditorTeam field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OnboardTenantPayload) GetGhEditorTeamOk() (*string, bool) {
	if o == nil || IsNil(o.GhEditorTeam) {
		return nil, false
	}
	return o.GhEditorTeam, true
}

// HasGhEditorTeam returns a boolean if a field has been set.
func (o *OnboardTenantPayload) HasGhEditorTeam() bool {
	if o != nil && !IsNil(o.GhEditorTeam) {
		return true
	}

	return false
}

// SetGhEditorTeam gets a reference to the given string and assigns it to the GhEditorTeam field.
func (o *OnboardTenantPayload) SetGhEditorTeam(v string) {
	o.GhEditorTeam = &v
}

// GetGhViewerTeam returns the GhViewerTeam field value if set, zero value otherwise.
func (o *OnboardTenantPayload) GetGhViewerTeam() string {
	if o == nil || IsNil(o.GhViewerTeam) {
		var ret string
		return ret
	}
	return *o.GhViewerTeam
}

// GetGhViewerTeamOk returns a tuple with the GhViewerTeam field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OnboardTenantPayload) GetGhViewerTeamOk() (*string, bool) {
	if o == nil || IsNil(o.GhViewerTeam) {
		return nil, false
	}
	return o.GhViewerTeam, true
}

// HasGhViewerTeam returns a boolean if a field has been set.
func (o *OnboardTenantPayload) HasGhViewerTeam() bool {
	if o != nil && !IsNil(o.GhViewerTeam) {
		return true
	}

	return false
}

// SetGhViewerTeam gets a reference to the given string and assigns it to the GhViewerTeam field.
func (o *OnboardTenantPayload) SetGhViewerTeam(v string) {
	o.GhViewerTeam = &v
}

// GetIamOrgId returns the IamOrgId field value if set, zero value otherwise.
func (o *OnboardTenantPayload) GetIamOrgId() string {
	if o == nil || IsNil(o.IamOrgId) {
		var ret string
		return ret
	}
	return *o.IamOrgId
}

// GetIamOrgIdOk returns a tuple with the IamOrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OnboardTenantPayload) GetIamOrgIdOk() (*string, bool) {
	if o == nil || IsNil(o.IamOrgId) {
		return nil, false
	}
	return o.IamOrgId, true
}

// HasIamOrgId returns a boolean if a field has been set.
func (o *OnboardTenantPayload) HasIamOrgId() bool {
	if o != nil && !IsNil(o.IamOrgId) {
		return true
	}

	return false
}

// SetIamOrgId gets a reference to the given string and assigns it to the IamOrgId field.
func (o *OnboardTenantPayload) SetIamOrgId(v string) {
	o.IamOrgId = &v
}

// GetIdToken returns the IdToken field value
func (o *OnboardTenantPayload) GetIdToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdToken
}

// GetIdTokenOk returns a tuple with the IdToken field value
// and a boolean to check if the value has been set.
func (o *OnboardTenantPayload) GetIdTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdToken, true
}

// SetIdToken sets field value
func (o *OnboardTenantPayload) SetIdToken(v string) {
	o.IdToken = v
}

// GetLogRetention returns the LogRetention field value if set, zero value otherwise.
func (o *OnboardTenantPayload) GetLogRetention() string {
	if o == nil || IsNil(o.LogRetention) {
		var ret string
		return ret
	}
	return *o.LogRetention
}

// GetLogRetentionOk returns a tuple with the LogRetention field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OnboardTenantPayload) GetLogRetentionOk() (*string, bool) {
	if o == nil || IsNil(o.LogRetention) {
		return nil, false
	}
	return o.LogRetention, true
}

// HasLogRetention returns a boolean if a field has been set.
func (o *OnboardTenantPayload) HasLogRetention() bool {
	if o != nil && !IsNil(o.LogRetention) {
		return true
	}

	return false
}

// SetLogRetention gets a reference to the given string and assigns it to the LogRetention field.
func (o *OnboardTenantPayload) SetLogRetention(v string) {
	o.LogRetention = &v
}

// GetMetricsRetention returns the MetricsRetention field value if set, zero value otherwise.
func (o *OnboardTenantPayload) GetMetricsRetention() string {
	if o == nil || IsNil(o.MetricsRetention) {
		var ret string
		return ret
	}
	return *o.MetricsRetention
}

// GetMetricsRetentionOk returns a tuple with the MetricsRetention field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OnboardTenantPayload) GetMetricsRetentionOk() (*string, bool) {
	if o == nil || IsNil(o.MetricsRetention) {
		return nil, false
	}
	return o.MetricsRetention, true
}

// HasMetricsRetention returns a boolean if a field has been set.
func (o *OnboardTenantPayload) HasMetricsRetention() bool {
	if o != nil && !IsNil(o.MetricsRetention) {
		return true
	}

	return false
}

// SetMetricsRetention gets a reference to the given string and assigns it to the MetricsRetention field.
func (o *OnboardTenantPayload) SetMetricsRetention(v string) {
	o.MetricsRetention = &v
}

// GetName returns the Name field value
func (o *OnboardTenantPayload) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OnboardTenantPayload) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OnboardTenantPayload) SetName(v string) {
	o.Name = v
}

// GetTraceRetention returns the TraceRetention field value if set, zero value otherwise.
func (o *OnboardTenantPayload) GetTraceRetention() string {
	if o == nil || IsNil(o.TraceRetention) {
		var ret string
		return ret
	}
	return *o.TraceRetention
}

// GetTraceRetentionOk returns a tuple with the TraceRetention field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OnboardTenantPayload) GetTraceRetentionOk() (*string, bool) {
	if o == nil || IsNil(o.TraceRetention) {
		return nil, false
	}
	return o.TraceRetention, true
}

// HasTraceRetention returns a boolean if a field has been set.
func (o *OnboardTenantPayload) HasTraceRetention() bool {
	if o != nil && !IsNil(o.TraceRetention) {
		return true
	}

	return false
}

// SetTraceRetention gets a reference to the given string and assigns it to the TraceRetention field.
func (o *OnboardTenantPayload) SetTraceRetention(v string) {
	o.TraceRetention = &v
}

func (o OnboardTenantPayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OnboardTenantPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Admins) {
		toSerialize["admins"] = o.Admins
	}
	toSerialize["aws_region"] = o.AwsRegion
	if !IsNil(o.GhEditorTeam) {
		toSerialize["gh_editor_team"] = o.GhEditorTeam
	}
	if !IsNil(o.GhViewerTeam) {
		toSerialize["gh_viewer_team"] = o.GhViewerTeam
	}
	if !IsNil(o.IamOrgId) {
		toSerialize["iam_org_id"] = o.IamOrgId
	}
	toSerialize["id_token"] = o.IdToken
	if !IsNil(o.LogRetention) {
		toSerialize["log_retention"] = o.LogRetention
	}
	if !IsNil(o.MetricsRetention) {
		toSerialize["metrics_retention"] = o.MetricsRetention
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.TraceRetention) {
		toSerialize["trace_retention"] = o.TraceRetention
	}
	return toSerialize, nil
}

func (o *OnboardTenantPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"aws_region",
		"id_token",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOnboardTenantPayload := _OnboardTenantPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOnboardTenantPayload)

	if err != nil {
		return err
	}

	*o = OnboardTenantPayload(varOnboardTenantPayload)

	return err
}

type NullableOnboardTenantPayload struct {
	value *OnboardTenantPayload
	isSet bool
}

func (v NullableOnboardTenantPayload) Get() *OnboardTenantPayload {
	return v.value
}

func (v *NullableOnboardTenantPayload) Set(val *OnboardTenantPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableOnboardTenantPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableOnboardTenantPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOnboardTenantPayload(val *OnboardTenantPayload) *NullableOnboardTenantPayload {
	return &NullableOnboardTenantPayload{value: val, isSet: true}
}

func (v NullableOnboardTenantPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOnboardTenantPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
