/*
Tenant mapper for HSP Logging 2.0

Service for managing tenants

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tenantmapper

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateKeyPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateKeyPayload{}

// CreateKeyPayload struct for CreateKeyPayload
type CreateKeyPayload struct {
	// The admin user
	Admin string `json:"admin"`
	// Expiry time time.Duration format. A value of 0s means no expiry
	Expiry string `json:"expiry"`
	// The format of the key
	Format string `json:"format"`
	// ID token
	IdToken string `json:"id_token"`
	// Name of the tenant
	Tenant string `json:"tenant"`
}

type _CreateKeyPayload CreateKeyPayload

// NewCreateKeyPayload instantiates a new CreateKeyPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateKeyPayload(admin string, expiry string, format string, idToken string, tenant string) *CreateKeyPayload {
	this := CreateKeyPayload{}
	this.Admin = admin
	this.Expiry = expiry
	this.Format = format
	this.IdToken = idToken
	this.Tenant = tenant
	return &this
}

// NewCreateKeyPayloadWithDefaults instantiates a new CreateKeyPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateKeyPayloadWithDefaults() *CreateKeyPayload {
	this := CreateKeyPayload{}
	return &this
}

// GetAdmin returns the Admin field value
func (o *CreateKeyPayload) GetAdmin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Admin
}

// GetAdminOk returns a tuple with the Admin field value
// and a boolean to check if the value has been set.
func (o *CreateKeyPayload) GetAdminOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Admin, true
}

// SetAdmin sets field value
func (o *CreateKeyPayload) SetAdmin(v string) {
	o.Admin = v
}

// GetExpiry returns the Expiry field value
func (o *CreateKeyPayload) GetExpiry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Expiry
}

// GetExpiryOk returns a tuple with the Expiry field value
// and a boolean to check if the value has been set.
func (o *CreateKeyPayload) GetExpiryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expiry, true
}

// SetExpiry sets field value
func (o *CreateKeyPayload) SetExpiry(v string) {
	o.Expiry = v
}

// GetFormat returns the Format field value
func (o *CreateKeyPayload) GetFormat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Format
}

// GetFormatOk returns a tuple with the Format field value
// and a boolean to check if the value has been set.
func (o *CreateKeyPayload) GetFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Format, true
}

// SetFormat sets field value
func (o *CreateKeyPayload) SetFormat(v string) {
	o.Format = v
}

// GetIdToken returns the IdToken field value
func (o *CreateKeyPayload) GetIdToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdToken
}

// GetIdTokenOk returns a tuple with the IdToken field value
// and a boolean to check if the value has been set.
func (o *CreateKeyPayload) GetIdTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdToken, true
}

// SetIdToken sets field value
func (o *CreateKeyPayload) SetIdToken(v string) {
	o.IdToken = v
}

// GetTenant returns the Tenant field value
func (o *CreateKeyPayload) GetTenant() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tenant
}

// GetTenantOk returns a tuple with the Tenant field value
// and a boolean to check if the value has been set.
func (o *CreateKeyPayload) GetTenantOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tenant, true
}

// SetTenant sets field value
func (o *CreateKeyPayload) SetTenant(v string) {
	o.Tenant = v
}

func (o CreateKeyPayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateKeyPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["admin"] = o.Admin
	toSerialize["expiry"] = o.Expiry
	toSerialize["format"] = o.Format
	toSerialize["id_token"] = o.IdToken
	toSerialize["tenant"] = o.Tenant
	return toSerialize, nil
}

func (o *CreateKeyPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"admin",
		"expiry",
		"format",
		"id_token",
		"tenant",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateKeyPayload := _CreateKeyPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateKeyPayload)

	if err != nil {
		return err
	}

	*o = CreateKeyPayload(varCreateKeyPayload)

	return err
}

type NullableCreateKeyPayload struct {
	value *CreateKeyPayload
	isSet bool
}

func (v NullableCreateKeyPayload) Get() *CreateKeyPayload {
	return v.value
}

func (v *NullableCreateKeyPayload) Set(val *CreateKeyPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateKeyPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateKeyPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateKeyPayload(val *CreateKeyPayload) *NullableCreateKeyPayload {
	return &NullableCreateKeyPayload{value: val, isSet: true}
}

func (v NullableCreateKeyPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateKeyPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
