/*
Tenant mapper for HSP Logging 2.0

Service for managing tenants

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tenantmapper

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateTenantPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTenantPayload{}

// UpdateTenantPayload struct for UpdateTenantPayload
type UpdateTenantPayload struct {
	// The admin claim of the tenant
	AdminClaim *string `json:"admin_claim,omitempty"`
	// Comma separated list of admins
	Admins *string `json:"admins,omitempty"`
	// The editor claim of the tenant
	EditorClaim *string `json:"editor_claim,omitempty"`
	// The log retention period of the tenant
	LogRetentionPeriod *string `json:"log_retention_period,omitempty"`
	// Logging support enabled for this tenant
	Logging *bool `json:"logging,omitempty"`
	// Metrics support enabled for this tenant
	Metrics *bool `json:"metrics,omitempty"`
	// The metrics retention period of the tenant
	MetricsRetentionPeriod *string `json:"metrics_retention_period,omitempty"`
	// Tenant ID
	TenantId string `json:"tenantId"`
	// The trace retention period of the tenant
	TraceRetentionPeriod *string `json:"trace_retention_period,omitempty"`
	// Tracing support enabled for this tenant
	Tracing *bool `json:"tracing,omitempty"`
	// The viewer claim of the tenant
	ViewerClaim *string `json:"viewer_claim,omitempty"`
}

type _UpdateTenantPayload UpdateTenantPayload

// NewUpdateTenantPayload instantiates a new UpdateTenantPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTenantPayload(tenantId string) *UpdateTenantPayload {
	this := UpdateTenantPayload{}
	this.TenantId = tenantId
	return &this
}

// NewUpdateTenantPayloadWithDefaults instantiates a new UpdateTenantPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTenantPayloadWithDefaults() *UpdateTenantPayload {
	this := UpdateTenantPayload{}
	return &this
}

// GetAdminClaim returns the AdminClaim field value if set, zero value otherwise.
func (o *UpdateTenantPayload) GetAdminClaim() string {
	if o == nil || IsNil(o.AdminClaim) {
		var ret string
		return ret
	}
	return *o.AdminClaim
}

// GetAdminClaimOk returns a tuple with the AdminClaim field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPayload) GetAdminClaimOk() (*string, bool) {
	if o == nil || IsNil(o.AdminClaim) {
		return nil, false
	}
	return o.AdminClaim, true
}

// HasAdminClaim returns a boolean if a field has been set.
func (o *UpdateTenantPayload) HasAdminClaim() bool {
	if o != nil && !IsNil(o.AdminClaim) {
		return true
	}

	return false
}

// SetAdminClaim gets a reference to the given string and assigns it to the AdminClaim field.
func (o *UpdateTenantPayload) SetAdminClaim(v string) {
	o.AdminClaim = &v
}

// GetAdmins returns the Admins field value if set, zero value otherwise.
func (o *UpdateTenantPayload) GetAdmins() string {
	if o == nil || IsNil(o.Admins) {
		var ret string
		return ret
	}
	return *o.Admins
}

// GetAdminsOk returns a tuple with the Admins field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPayload) GetAdminsOk() (*string, bool) {
	if o == nil || IsNil(o.Admins) {
		return nil, false
	}
	return o.Admins, true
}

// HasAdmins returns a boolean if a field has been set.
func (o *UpdateTenantPayload) HasAdmins() bool {
	if o != nil && !IsNil(o.Admins) {
		return true
	}

	return false
}

// SetAdmins gets a reference to the given string and assigns it to the Admins field.
func (o *UpdateTenantPayload) SetAdmins(v string) {
	o.Admins = &v
}

// GetEditorClaim returns the EditorClaim field value if set, zero value otherwise.
func (o *UpdateTenantPayload) GetEditorClaim() string {
	if o == nil || IsNil(o.EditorClaim) {
		var ret string
		return ret
	}
	return *o.EditorClaim
}

// GetEditorClaimOk returns a tuple with the EditorClaim field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPayload) GetEditorClaimOk() (*string, bool) {
	if o == nil || IsNil(o.EditorClaim) {
		return nil, false
	}
	return o.EditorClaim, true
}

// HasEditorClaim returns a boolean if a field has been set.
func (o *UpdateTenantPayload) HasEditorClaim() bool {
	if o != nil && !IsNil(o.EditorClaim) {
		return true
	}

	return false
}

// SetEditorClaim gets a reference to the given string and assigns it to the EditorClaim field.
func (o *UpdateTenantPayload) SetEditorClaim(v string) {
	o.EditorClaim = &v
}

// GetLogRetentionPeriod returns the LogRetentionPeriod field value if set, zero value otherwise.
func (o *UpdateTenantPayload) GetLogRetentionPeriod() string {
	if o == nil || IsNil(o.LogRetentionPeriod) {
		var ret string
		return ret
	}
	return *o.LogRetentionPeriod
}

// GetLogRetentionPeriodOk returns a tuple with the LogRetentionPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPayload) GetLogRetentionPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.LogRetentionPeriod) {
		return nil, false
	}
	return o.LogRetentionPeriod, true
}

// HasLogRetentionPeriod returns a boolean if a field has been set.
func (o *UpdateTenantPayload) HasLogRetentionPeriod() bool {
	if o != nil && !IsNil(o.LogRetentionPeriod) {
		return true
	}

	return false
}

// SetLogRetentionPeriod gets a reference to the given string and assigns it to the LogRetentionPeriod field.
func (o *UpdateTenantPayload) SetLogRetentionPeriod(v string) {
	o.LogRetentionPeriod = &v
}

// GetLogging returns the Logging field value if set, zero value otherwise.
func (o *UpdateTenantPayload) GetLogging() bool {
	if o == nil || IsNil(o.Logging) {
		var ret bool
		return ret
	}
	return *o.Logging
}

// GetLoggingOk returns a tuple with the Logging field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPayload) GetLoggingOk() (*bool, bool) {
	if o == nil || IsNil(o.Logging) {
		return nil, false
	}
	return o.Logging, true
}

// HasLogging returns a boolean if a field has been set.
func (o *UpdateTenantPayload) HasLogging() bool {
	if o != nil && !IsNil(o.Logging) {
		return true
	}

	return false
}

// SetLogging gets a reference to the given bool and assigns it to the Logging field.
func (o *UpdateTenantPayload) SetLogging(v bool) {
	o.Logging = &v
}

// GetMetrics returns the Metrics field value if set, zero value otherwise.
func (o *UpdateTenantPayload) GetMetrics() bool {
	if o == nil || IsNil(o.Metrics) {
		var ret bool
		return ret
	}
	return *o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPayload) GetMetricsOk() (*bool, bool) {
	if o == nil || IsNil(o.Metrics) {
		return nil, false
	}
	return o.Metrics, true
}

// HasMetrics returns a boolean if a field has been set.
func (o *UpdateTenantPayload) HasMetrics() bool {
	if o != nil && !IsNil(o.Metrics) {
		return true
	}

	return false
}

// SetMetrics gets a reference to the given bool and assigns it to the Metrics field.
func (o *UpdateTenantPayload) SetMetrics(v bool) {
	o.Metrics = &v
}

// GetMetricsRetentionPeriod returns the MetricsRetentionPeriod field value if set, zero value otherwise.
func (o *UpdateTenantPayload) GetMetricsRetentionPeriod() string {
	if o == nil || IsNil(o.MetricsRetentionPeriod) {
		var ret string
		return ret
	}
	return *o.MetricsRetentionPeriod
}

// GetMetricsRetentionPeriodOk returns a tuple with the MetricsRetentionPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPayload) GetMetricsRetentionPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.MetricsRetentionPeriod) {
		return nil, false
	}
	return o.MetricsRetentionPeriod, true
}

// HasMetricsRetentionPeriod returns a boolean if a field has been set.
func (o *UpdateTenantPayload) HasMetricsRetentionPeriod() bool {
	if o != nil && !IsNil(o.MetricsRetentionPeriod) {
		return true
	}

	return false
}

// SetMetricsRetentionPeriod gets a reference to the given string and assigns it to the MetricsRetentionPeriod field.
func (o *UpdateTenantPayload) SetMetricsRetentionPeriod(v string) {
	o.MetricsRetentionPeriod = &v
}

// GetTenantId returns the TenantId field value
func (o *UpdateTenantPayload) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *UpdateTenantPayload) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *UpdateTenantPayload) SetTenantId(v string) {
	o.TenantId = v
}

// GetTraceRetentionPeriod returns the TraceRetentionPeriod field value if set, zero value otherwise.
func (o *UpdateTenantPayload) GetTraceRetentionPeriod() string {
	if o == nil || IsNil(o.TraceRetentionPeriod) {
		var ret string
		return ret
	}
	return *o.TraceRetentionPeriod
}

// GetTraceRetentionPeriodOk returns a tuple with the TraceRetentionPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPayload) GetTraceRetentionPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.TraceRetentionPeriod) {
		return nil, false
	}
	return o.TraceRetentionPeriod, true
}

// HasTraceRetentionPeriod returns a boolean if a field has been set.
func (o *UpdateTenantPayload) HasTraceRetentionPeriod() bool {
	if o != nil && !IsNil(o.TraceRetentionPeriod) {
		return true
	}

	return false
}

// SetTraceRetentionPeriod gets a reference to the given string and assigns it to the TraceRetentionPeriod field.
func (o *UpdateTenantPayload) SetTraceRetentionPeriod(v string) {
	o.TraceRetentionPeriod = &v
}

// GetTracing returns the Tracing field value if set, zero value otherwise.
func (o *UpdateTenantPayload) GetTracing() bool {
	if o == nil || IsNil(o.Tracing) {
		var ret bool
		return ret
	}
	return *o.Tracing
}

// GetTracingOk returns a tuple with the Tracing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPayload) GetTracingOk() (*bool, bool) {
	if o == nil || IsNil(o.Tracing) {
		return nil, false
	}
	return o.Tracing, true
}

// HasTracing returns a boolean if a field has been set.
func (o *UpdateTenantPayload) HasTracing() bool {
	if o != nil && !IsNil(o.Tracing) {
		return true
	}

	return false
}

// SetTracing gets a reference to the given bool and assigns it to the Tracing field.
func (o *UpdateTenantPayload) SetTracing(v bool) {
	o.Tracing = &v
}

// GetViewerClaim returns the ViewerClaim field value if set, zero value otherwise.
func (o *UpdateTenantPayload) GetViewerClaim() string {
	if o == nil || IsNil(o.ViewerClaim) {
		var ret string
		return ret
	}
	return *o.ViewerClaim
}

// GetViewerClaimOk returns a tuple with the ViewerClaim field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPayload) GetViewerClaimOk() (*string, bool) {
	if o == nil || IsNil(o.ViewerClaim) {
		return nil, false
	}
	return o.ViewerClaim, true
}

// HasViewerClaim returns a boolean if a field has been set.
func (o *UpdateTenantPayload) HasViewerClaim() bool {
	if o != nil && !IsNil(o.ViewerClaim) {
		return true
	}

	return false
}

// SetViewerClaim gets a reference to the given string and assigns it to the ViewerClaim field.
func (o *UpdateTenantPayload) SetViewerClaim(v string) {
	o.ViewerClaim = &v
}

func (o UpdateTenantPayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTenantPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AdminClaim) {
		toSerialize["admin_claim"] = o.AdminClaim
	}
	if !IsNil(o.Admins) {
		toSerialize["admins"] = o.Admins
	}
	if !IsNil(o.EditorClaim) {
		toSerialize["editor_claim"] = o.EditorClaim
	}
	if !IsNil(o.LogRetentionPeriod) {
		toSerialize["log_retention_period"] = o.LogRetentionPeriod
	}
	if !IsNil(o.Logging) {
		toSerialize["logging"] = o.Logging
	}
	if !IsNil(o.Metrics) {
		toSerialize["metrics"] = o.Metrics
	}
	if !IsNil(o.MetricsRetentionPeriod) {
		toSerialize["metrics_retention_period"] = o.MetricsRetentionPeriod
	}
	toSerialize["tenantId"] = o.TenantId
	if !IsNil(o.TraceRetentionPeriod) {
		toSerialize["trace_retention_period"] = o.TraceRetentionPeriod
	}
	if !IsNil(o.Tracing) {
		toSerialize["tracing"] = o.Tracing
	}
	if !IsNil(o.ViewerClaim) {
		toSerialize["viewer_claim"] = o.ViewerClaim
	}
	return toSerialize, nil
}

func (o *UpdateTenantPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateTenantPayload := _UpdateTenantPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateTenantPayload)

	if err != nil {
		return err
	}

	*o = UpdateTenantPayload(varUpdateTenantPayload)

	return err
}

type NullableUpdateTenantPayload struct {
	value *UpdateTenantPayload
	isSet bool
}

func (v NullableUpdateTenantPayload) Get() *UpdateTenantPayload {
	return v.value
}

func (v *NullableUpdateTenantPayload) Set(val *UpdateTenantPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTenantPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTenantPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTenantPayload(val *UpdateTenantPayload) *NullableUpdateTenantPayload {
	return &NullableUpdateTenantPayload{value: val, isSet: true}
}

func (v NullableUpdateTenantPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTenantPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
