/*
Tenant mapper for HSP Logging 2.0

Service for managing tenants

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tenantmapper

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Tenantlist type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Tenantlist{}

// Tenantlist struct for Tenantlist
type Tenantlist struct {
	// List of tenants
	Tenants []Tenant `json:"tenants"`
}

type _Tenantlist Tenantlist

// NewTenantlist instantiates a new Tenantlist object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantlist(tenants []Tenant) *Tenantlist {
	this := Tenantlist{}
	this.Tenants = tenants
	return &this
}

// NewTenantlistWithDefaults instantiates a new Tenantlist object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantlistWithDefaults() *Tenantlist {
	this := Tenantlist{}
	return &this
}

// GetTenants returns the Tenants field value
func (o *Tenantlist) GetTenants() []Tenant {
	if o == nil {
		var ret []Tenant
		return ret
	}

	return o.Tenants
}

// GetTenantsOk returns a tuple with the Tenants field value
// and a boolean to check if the value has been set.
func (o *Tenantlist) GetTenantsOk() ([]Tenant, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tenants, true
}

// SetTenants sets field value
func (o *Tenantlist) SetTenants(v []Tenant) {
	o.Tenants = v
}

func (o Tenantlist) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Tenantlist) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenants"] = o.Tenants
	return toSerialize, nil
}

func (o *Tenantlist) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenants",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenantlist := _Tenantlist{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTenantlist)

	if err != nil {
		return err
	}

	*o = Tenantlist(varTenantlist)

	return err
}

type NullableTenantlist struct {
	value *Tenantlist
	isSet bool
}

func (v NullableTenantlist) Get() *Tenantlist {
	return v.value
}

func (v *NullableTenantlist) Set(val *Tenantlist) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantlist) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantlist) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantlist(val *Tenantlist) *NullableTenantlist {
	return &NullableTenantlist{value: val, isSet: true}
}

func (v NullableTenantlist) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantlist) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
